# Generated by Django 6.0.1 on 2026-02-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eclectronic',
            new_name='electronic',
        ),
    ]
