# Generated by Django 6.0.1 on 2026-02-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1_app', '0002_rename_eclectronic_electronic'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='electronic',
        ),
    ]
